train_set:
  module: cabrnet.core.utils.load_3d
  name: load_torch_dataset
  params:
    path: data/prostate/test
    augment: false
    RGB: false
  batch_size: 2
  shuffle: true

projection_set:
  module: cabrnet.core.utils.load_3d
  name: load_torch_dataset
  params:
    path: data/prostate/test
    augment: false
    RGB: false
  batch_size: 2
  shuffle: false

validation_set:
  module: cabrnet.core.utils.load_3d
  name: load_torch_dataset
  params:
    path: data/prostate/valid
    augment: false
    RGB: false
  batch_size: 2
  shuffle: false

test_set:
  module: cabrnet.core.utils.load_3d
  name: load_torch_dataset
  params:
    path: data/prostate/train
    augment: false
    RGB: false
  batch_size: 2
  shuffle: false
