train_set:
  module: cabrnet.core.utils.load3d
  name: load_torch_dataset
  params:
    path: data/prostate/train
    augment: true
  batch_size: 8
  shuffle: true

projection_set:
  module: cabrnet.core.utils.load3d
  name: load_torch_dataset
  params:
    path: data/prostate/train
    augment: false
  batch_size: 8
  shuffle: false

validation_set:
  module: cabrnet.core.utils.load3d
  name: load_torch_dataset
  params:
    path: data/prostate/valid
    augment: false
  batch_size: 8
  shuffle: false

test_set:
  module: cabrnet.core.utils.load3d
  name: load_torch_dataset
  params:
    path: data/prostate/test
    augment: false
  batch_size: 8
  shuffle: false
