top_arch:
  module: cabrnet.baseline.model
  name: Baseline

extractor:
  backbone:
    module: torch.hub
    arch: r2plus1d_r50
    layer: blocks.5.dropout
    repo_or_dir: facebookresearch/pytorchvideo
    pretrained: True
  add_on:
    flatten:
      type: Flatten
    bottleneck:
      type: Linear
      params:
        in_features: 2048
        out_features: 64
        bias: True
    act:
      type: ReLU
    decision:
      type: Linear
      params:
        in_features: 64
        out_features: 2
        bias: True

similarity:
  ProtoPNetSimilarity

classifier:
  module: cabrnet.baseline.decision
  name: DummyClassifier
  params:
    num_classes: 2
