train_set:
  module: cabrnet.core.utils.load_3d
  name: load_kinetics400
  params:
    path: data/kinetics
    split: train
  batch_size: 8
  shuffle: true

projection_set:
  module: cabrnet.core.utils.load_3d
  name: load_kinetics400
  params:
    path: data/kinetics
    split: train
  batch_size: 8
  shuffle: false

validation_set:
  module: cabrnet.core.utils.load_3d
  name: load_kinetics400
  params:
    path: data/kinetics
    split: val
  batch_size: 8
  shuffle: false

test_set:
  module: cabrnet.core.utils.load_3d
  name: load_kinetics400
  params:
    path: data/kinetics
    split: test
  batch_size: 8
  shuffle: false
