train_set:
  module: cabrnet.core.utils.load3d
  name: load_kinetics400
  params:
    path: data/kinetics
    split: val
  batch_size: 2
  shuffle: true

projection_set:
  module: cabrnet.core.utils.load3d
  name: load_kinetics400
  params:
    path: data/kinetics
    split: val
  batch_size: 2
  shuffle: false

validation_set:
  module: cabrnet.core.utils.load3d
  name: load_kinetics400
  params:
    path: data/kinetics
    split: val
  batch_size: 2
  shuffle: false

test_set:
  module: cabrnet.core.utils.load3d
  name: load_kinetics400
  params:
    path: data/kinetics
    split: val
  batch_size: 2
  shuffle: false
