top_arch:
  module: cabrnet.archs.baseline.model
  name: Baseline

extractor:
  backbone:
    module: torch.hub
    arch: r2plus1d_r50
    layer: blocks.4.res_blocks.2.activation
    repo_or_dir: facebookresearch/pytorchvideo
    pretrained: True
  add_on:
    conv0:
      type: Conv3d
      params:
        in_channels: 2048
        out_channels: 2048
        kernel_size: [2,2,3]
        stride: [1,2,3]
        padding: 0
    pool:
      type: AvgPool3d
      params:
        kernel_size: [1,3,3]
        stride: 1
    dropout:
      type: Dropout
      params:
        p: 0.5
        inplace: False
    flatten:
      type: Flatten
    bottleneck:
      type: Linear
      params:
        in_features: 2048
        out_features: 64
        bias: True
    act:
      type: ReLU
    decision:
      type: Linear
      params:
        in_features: 64
        out_features: 2
        bias: True
    activation:
      type: Softmax

similarity:
  ProtoPNet3DSimilarity

classifier:
  module: cabrnet.archs.baseline.decision
  name: DummyClassifier
  params:
    num_classes: 2
