param_groups:
  backbone: extractor.convnet
  addons: extractor.add_on

optimizers:
  # Main optimizer
  joint_optimizer:
    type: Adam
    groups:
      backbone:
        lr: 0.00001
        weight_decay: 0.001
      addons:
        lr: 0.0001
        weight_decay: 0.001

num_epochs: 25
periods:
  main_training:
    optimizers: joint_optimizer
