param_groups:
  backbone: extractor.convnet
  addons: extractor.add_on

optimizers:
  # Main optimizer
  joint_optimizer:
    type: Adam
    groups:
      addons:
        lr: 0.001
        weight_decay: 0.001

num_epochs: 50
periods:
  main_training:
    freeze: [ backbone ]
    optimizers: joint_optimizer
