param_groups:
  backbone: extractor.convnet
  prototypes: classifier.prototypes
  last_layer: classifier.last_layer

optimizers:
  # Optimizer used during the first epochs
  warmup_optimizer:
    type: Adam 
    groups:
      prototypes:
        lr: 0.001
      last_layer:
        lr: 0.001

  # Main optimizer
  joint_optimizer:
    type: Adam
    groups:
      backbone:
        lr: 0.00001
        weight_decay: 0.001
      prototypes:
        lr: 0.0001
        weight_decay: 0.001

periods:
  warmup:
    num_epochs: 5
    freeze: [ backbone ]
    optimizers: warmup_optimizer
  main_training:
    num_epochs: 25
    freeze: [ last_layer ]
    optimizers: joint_optimizer

auxiliary_info:
  loss_coefficients:
    clustering: 0.8
    separability: -0.08
    regularization: 0.001
    cross_entropy: 1000.0
  projection_config:
    start_epoch: 500
    frequency: 5
    num_ft_epochs: 1

epilogue:
  pruning_threshold: 3
  num_nearest_patches: 6
  num_fine_tuning_epochs: 1