train_set:
  module: cabrnet.core.utils.load_3d
  name: load_kinetics_new
  params:
    path: data/kinetics
    split: test
    duration_sec: 3
    num_frames: 5
  batch_size: 8
  shuffle: true

projection_set:
  module: cabrnet.core.utils.load_3d
  name: load_kinetics_new
  params:
    path: data/kinetics
    split: test
    duration_sec: 3
    num_frames: 5
  batch_size: 8
  shuffle: false

validation_set:
  module: cabrnet.core.utils.load_3d
  name: load_kinetics_new
  params:
    path: data/kinetics
    split: test
    duration_sec: 3
    num_frames: 5
  batch_size: 8
  shuffle: false

test_set:
  module: cabrnet.core.utils.load_3d
  name: load_kinetics_new
  params:
    path: data/kinetics
    split: test
    duration_sec: 3
    num_frames: 5
  batch_size: 8
  shuffle: false
