top_arch:
  module: cabrnet.archs.protopnet3d.model
  name: ProtoPNet3D

extractor:
  backbone:
    module: torch.hub
    arch: r2plus1d_r50
    layer: blocks.4.res_blocks.2.activation
    repo_or_dir: facebookresearch/pytorchvideo
    pretrained: True
  add_on:
    pool:
      type: AvgPool3d
      params:
        kernel_size: [ 2,2,2 ]
        stride: 1
    act1:
      type: ReLU
    conv:
      type: Conv3d
      params:
        in_channels: 2048
        out_channels: 512
        kernel_size: 1
        bias: True
    act2:
      type: Sigmoid

similarity:
  name: ProtoPNet3DSimilarity

classifier:
  module: cabrnet.archs.protopnet3d.decision
  name: ProtoPNet3DClassifier
  params:
    num_features: 512
    num_classes: 2
    num_proto_per_class: 5
    proto_init_mode: SHIFTED_NORMAL
