param_groups:
  backbone: extractor.convnet
  add_on: extractor.add_on
  prototypes: classifier.prototypes
  last_layer: classifier.last_layer

optimizers:
  # Optimizer used during the first epochs
  warmup_optimizer:
    type: Adam
    groups:
      add_on:
        lr: 0.001
      prototypes:
        lr: 0.001
      last_layer:
        lr: 0.001

  # Main optimizer
  joint_optimizer:
    type: Adam
    groups:
      add_on:
        lr: 0.0001
        weight_decay: 0.001
      prototypes:
        lr: 0.0001
        weight_decay: 0.001

  # mandatory for prototype projection phase
  last_layer_optimizer:
    type: Adam
    groups:
      last_layer:
        lr: 0.0001

num_epochs: 30

periods:
  warmup:
    num_epochs: 7
    freeze: [ backbone ]
    optimizers: warmup_optimizer
  main_training:
    freeze: [ backbone, last_layer ]
    optimizers: joint_optimizer

auxiliary_info:
  loss_coefficients:
    clustering: 0.8
    separability: -0.08
    regularization: 0.001
    cross_entropy: 1.0
  projection_config:
    start_epoch: 17
    frequency: 5
    num_ft_epochs: 1

epilogue:
  pruning_threshold: 3
  num_nearest_patches: 6
  num_fine_tuning_epochs: 1