train_set:
  module: cabrnet.core.utils.load_numpy
  name: load_torch_dataset
  params:
    path: data/prostate/train
  batch_size: 4
  shuffle: true

projection_set:
  module: cabrnet.core.utils.load_numpy
  name: load_torch_dataset
  params:
    path: data/prostate/train
  batch_size: 4
  shuffle: false

test_set:
  module: cabrnet.core.utils.load_numpy
  name: load_torch_dataset
  params:
    path: data/prostate/test
  batch_size: 4
  shuffle: false
