train_set:
  module: cabrnet.core.utils.load_numpy
  name: load_zeros
  params:
    in_shape: [16,256,256]
    size: 10
  batch_size: 2
  shuffle: true

projection_set:
  module: cabrnet.core.utils.load_numpy
  name: load_zeros
  params:
    in_shape: [16,256,256]
    size: 10
  batch_size: 2
  shuffle: false

test_set:
  module: cabrnet.core.utils.load_numpy
  name: load_zeros
  params:
    in_shape: [16,256,256]
    size: 10
  batch_size: 2
  shuffle: false
