train_set:
  module: cabrnet.core.utils.load_numpy
  name: load_numpy_dataset
  params:
    path: data/dbt/train
  batch_size: 2
  shuffle: true

projection_set:
  module: cabrnet.core.utils.load_numpy
  name: load_numpy_dataset
  params:
    path: data/dbt/train
  batch_size: 2
  shuffle: false

test_set:
  module: cabrnet.core.utils.load_numpy
  name: load_numpy_dataset
  params:
    path: data/dbt/test
  batch_size: 2
  shuffle: false
