top_arch:
  module: cabrnet.archs.protopnet3d.model
  name: ProtoPNet3D

extractor:
  backbone:
    module: torch.hub
    arch: r2plus1d_r50
    layer: blocks.5.dropout
    repo_or_dir: facebookresearch/pytorchvideo
    pretrained: True
  add_on:
    init_mode: XAVIER
    conv1:
      type: Conv2d
      params:
        out_channels: 128
        kernel_size: 1
        bias: False
    sigmoid1:
      type: Sigmoid

similarity:
  name: ProtoPNetSimilarity

classifier:
  module: cabrnet.archs.protopnet3d.decision
  name: ProtoPNet3DClassifier
  params:
    num_classes: 10
    num_proto_per_class: 10
    proto_init_mode: SHIFTED_NORMAL
