top_arch:
  module: cabrnet.archs.protopnet3d.model
  name: ProtoPNet3D

extractor:
  backbone:
    module: torch.hub
    arch: r2plus1d_r50
    layer: blocks.5.dropout
    repo_or_dir: facebookresearch/pytorchvideo
    pretrained: True

similarity:
  name: ProtoPNet3DSimilarity

classifier:
  module: cabrnet.archs.protopnet3d.decision
  name: ProtoPNet3DClassifier
  params:
    num_classes: 2
    num_proto_per_class: 3
    proto_init_mode: SHIFTED_NORMAL
