param_groups:
  backbone: extractor.convnet
  prototypes: classifier.prototypes
  last_layer: classifier.last_layer

optimizers:
  joint_optimizer:
    type: Adam
    groups:
      backbone:
        lr: 0.00001
        weight_decay_rate: 0.01
        momentum: 0.9
      prototypes:
        lr: 0.00001
        weight_decay_rate: 0.01
        momentum: 0.9
  last_layer_optimizer:
    type: Adam
    groups:
      last_layer:
        lr: 0.000001

num_epochs: 50

periods:
  main_training:
    patience: 30
    epoch_range: [0, 50]
    optimizers: joint_optimizer

auxiliary_info:
  loss_coefficients:
    clustering: 0.8
    separability: -0.08
    regularization: 0.0001
  projection_config:
    start_epoch: 26
    frequency: 5
    num_ft_epochs: 1

epilogue:
  pruning_threshold: 3
  num_nearest_patches: 6
  num_fine_tuning_epochs: 1
